lasynsec_front_homepage:
    path:     /
    defaults: { _controller: LasynsecFrontBundle:Static:homepage }

lasynsec_front_about:
    path:    /about
    defaults: { _controller: LasynsecFrontBundle:Static:about }

lasynsec_front_user_timeline:
    path:    /timeline{userId}
    defaults: { _controller: LasynsecFrontBundle:Timeline:userTimeline }